import type { Recall } from '../types/recall'
export const mockRecalls: Recall[] = [
  { id:"F-1001-2026", recallNumber:"F-1001-2026", eventId:"90001", productDescription:"Jalapeño Peppers, 1lb bag - Sinaloa, Mexico (Coast Citrus Distributors)", reasonForRecall:"Potential Salmonella contamination", classification:"Class I", status:"Ongoing", distributionPattern:"CA, AZ, TX, NM, nationwide", recallingFirm:"Coast Citrus Distributors", city:"San Diego", state:"CA", country:"United States", recallInitiationDate:"20260115", productType:"Food", codeInfo:"Lot #SJ-2026-0110", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"1200 Harbor Blvd", address2:"", postalCode:"92101", centerClassificationDate:"20260120", initialFirmNotification:"Letter", productQuantity:"2,400 bags", terminationDate:"", source:"FDA" },
  { id:"F-1002-2026", recallNumber:"F-1002-2026", eventId:"90002", productDescription:"Powdered Whole Milk, 25kg bags - California Dairies Inc", reasonForRecall:"Salmonella contamination - FDA CORE investigation", classification:"Class I", status:"Ongoing", distributionPattern:"Nationwide, exported to Mexico", recallingFirm:"California Dairies Inc", city:"Visalia", state:"CA", country:"United States", recallInitiationDate:"20260220", productType:"Food", codeInfo:"Codes 01186-02286", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"3500 Dairy Rd", address2:"Suite 200", postalCode:"93291", centerClassificationDate:"20260225", initialFirmNotification:"Press Release", productQuantity:"500 bags", terminationDate:"", source:"FDA" },
  { id:"F-0988-2025", recallNumber:"F-0988-2025", eventId:"89012", productDescription:"Prepared Pasta Meals with Chicken & Vegetables, 12oz", reasonForRecall:"Potential Listeria monocytogenes contamination", classification:"Class I", status:"Completed", distributionPattern:"Nationwide - retail", recallingFirm:"Fresh Pasta Co", city:"Chicago", state:"IL", country:"United States", recallInitiationDate:"20250610", productType:"Food", codeInfo:"Best by 06/20/2025", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"800 W Industrial Ave", address2:"", postalCode:"60607", centerClassificationDate:"20250615", initialFirmNotification:"Telephone", productQuantity:"8,000 units", terminationDate:"20250901", source:"FDA" },
  { id:"F-1100-2026", recallNumber:"F-1100-2026", eventId:"90010", productDescription:"Dark Chocolate Bar with Sea Salt, 3oz", reasonForRecall:"Undeclared milk and soy allergens", classification:"Class I", status:"Ongoing", distributionPattern:"NY, NJ, CT, PA", recallingFirm:"Artisan Chocolate LLC", city:"Brooklyn", state:"NY", country:"United States", recallInitiationDate:"20260301", productType:"Food", codeInfo:"Lot C0426", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"45 Wythe Ave", address2:"", postalCode:"11249", centerClassificationDate:"20260305", initialFirmNotification:"Letter", productQuantity:"1,200 bars", terminationDate:"", source:"FDA" },
  { id:"F-1101-2026", recallNumber:"F-1101-2026", eventId:"90011", productDescription:"Salsa Verde, 16oz jar", reasonForRecall:"Undeclared wheat allergen", classification:"Class II", status:"Ongoing", distributionPattern:"TX, OK, LA", recallingFirm:"Salsa Fresca Foods", city:"Austin", state:"TX", country:"United States", recallInitiationDate:"20260210", productType:"Food", codeInfo:"Best by 08/2026", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"2100 E Cesar Chavez", address2:"", postalCode:"78702", centerClassificationDate:"20260214", initialFirmNotification:"Letter", productQuantity:"3,600 jars", terminationDate:"", source:"FDA" },
  { id:"F-1102-2026", recallNumber:"F-1102-2026", eventId:"90012", productDescription:"Frozen Beef Taquitos, 20ct", reasonForRecall:"Foreign matter - plastic fragments", classification:"Class II", status:"Terminated", distributionPattern:"Nationwide", recallingFirm:"Frozen Foods Inc", city:"Denver", state:"CO", country:"United States", recallInitiationDate:"20260128", productType:"Food", codeInfo:"Lot T-2026-01", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"5500 S Federal Blvd", address2:"", postalCode:"80123", centerClassificationDate:"20260201", initialFirmNotification:"Press Release", productQuantity:"15,000 boxes", terminationDate:"20260415", source:"FDA" },
  { id:"F-1103-2026", recallNumber:"F-1103-2026", eventId:"90013", productDescription:"Aquafaba Powder, 500g", reasonForRecall:"Undeclared egg allergen", classification:"Class I", status:"Ongoing", distributionPattern:"Nationwide - online", recallingFirm:"Plant Protein Co", city:"Portland", state:"OR", country:"United States", recallInitiationDate:"20260310", productType:"Food", codeInfo:"Batch AP-033", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"920 SE Division St", address2:"", postalCode:"97214", centerClassificationDate:"20260314", initialFirmNotification:"Letter", productQuantity:"800 pouches", terminationDate:"", source:"FDA" },
  { id:"F-1104-2026", recallNumber:"F-1104-2026", eventId:"90014", productDescription:"Moringa Leaf Powder, 8oz pouch", reasonForRecall:"Salmonella - FDA CORE active investigation (Jan/Feb 2026)", classification:"Class I", status:"Ongoing", distributionPattern:"Nationwide", recallingFirm:"Green Superfoods LLC", city:"Miami", state:"FL", country:"United States", recallInitiationDate:"20260120", productType:"Food", codeInfo:"Lot M-0126", moreCodeInfo:"Lots 8L5M30, 8L5M31, 8L5M32 — continuation from FDA more_code_info field (regression fixture for F-2258-2016 style record)", voluntaryMandated:"Voluntary: Firm Initiated", address1:"1800 Biscayne Blvd", address2:"Unit 4B", postalCode:"33132", centerClassificationDate:"20260125", initialFirmNotification:"Press Release", productQuantity:"4,200 pouches", terminationDate:"", source:"FDA" },
]
