import type { Recall } from '../types/recall'
// Invented records for an explicitly labeled interface demo, never a fallback.
export const mockRecalls: Recall[] = [
  { id:"F-1001-2026", recallNumber:"F-1001-2026", eventId:"90001", productDescription:"Jalapeño Peppers, 1lb bag", reasonForRecall:"Potential Salmonella contamination", classification:"Class I", status:"Ongoing", distributionPattern:"CA, AZ, TX, NM, nationwide", recallingFirm:"Demo Produce 01 (fictional)", city:"San Diego", state:"CA", country:"United States", recallInitiationDate:"20260115", productType:"Food", codeInfo:"Lot #SJ-2026-0110", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 01 (fictional)", address2:"", postalCode:"92101", centerClassificationDate:"20260120", initialFirmNotification:"Letter", productQuantity:"2,400 bags", terminationDate:"" },
  { id:"F-1002-2026", recallNumber:"F-1002-2026", eventId:"90002", productDescription:"Powdered Whole Milk, 25kg bags", reasonForRecall:"Potential Salmonella contamination", classification:"Class I", status:"Ongoing", distributionPattern:"Nationwide, exported to Mexico", recallingFirm:"Demo Dairy 02 (fictional)", city:"Visalia", state:"CA", country:"United States", recallInitiationDate:"20260220", productType:"Food", codeInfo:"Codes 01186-02286", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 02 (fictional)", address2:"Suite 200", postalCode:"93291", centerClassificationDate:"20260225", initialFirmNotification:"Press Release", productQuantity:"500 bags", terminationDate:"" },
  { id:"F-0988-2025", recallNumber:"F-0988-2025", eventId:"89012", productDescription:"Prepared Pasta Meals with Chicken & Vegetables, 12oz", reasonForRecall:"Potential Listeria monocytogenes contamination", classification:"Class I", status:"Completed", distributionPattern:"Nationwide - retail", recallingFirm:"Demo Kitchen 03 (fictional)", city:"Chicago", state:"IL", country:"United States", recallInitiationDate:"20250610", productType:"Food", codeInfo:"Best by 06/20/2025", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 03 (fictional)", address2:"", postalCode:"60607", centerClassificationDate:"20250615", initialFirmNotification:"Telephone", productQuantity:"8,000 units", terminationDate:"20250901" },
  { id:"F-1100-2026", recallNumber:"F-1100-2026", eventId:"90010", productDescription:"Dark Chocolate Bar with Sea Salt, 3oz", reasonForRecall:"Undeclared milk and soy allergens", classification:"Class I", status:"Ongoing", distributionPattern:"NY, NJ, CT, PA", recallingFirm:"Demo Chocolate 04 (fictional)", city:"Brooklyn", state:"NY", country:"United States", recallInitiationDate:"20260301", productType:"Food", codeInfo:"Lot C0426", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 04 (fictional)", address2:"", postalCode:"11249", centerClassificationDate:"20260305", initialFirmNotification:"Letter", productQuantity:"1,200 bars", terminationDate:"" },
  { id:"F-1101-2026", recallNumber:"F-1101-2026", eventId:"90011", productDescription:"Salsa Verde, 16oz jar", reasonForRecall:"Undeclared wheat allergen", classification:"Class II", status:"Ongoing", distributionPattern:"TX, OK, LA", recallingFirm:"Demo Pantry 05 (fictional)", city:"Austin", state:"TX", country:"United States", recallInitiationDate:"20260210", productType:"Food", codeInfo:"Best by 08/2026", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 05 (fictional)", address2:"", postalCode:"78702", centerClassificationDate:"20260214", initialFirmNotification:"Letter", productQuantity:"3,600 jars", terminationDate:"" },
  { id:"F-1102-2026", recallNumber:"F-1102-2026", eventId:"90012", productDescription:"Frozen Beef Taquitos, 20ct", reasonForRecall:"Foreign matter - plastic fragments", classification:"Class II", status:"Terminated", distributionPattern:"Nationwide", recallingFirm:"Demo Freezer 06 (fictional)", city:"Denver", state:"CO", country:"United States", recallInitiationDate:"20260128", productType:"Food", codeInfo:"Lot T-2026-01", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 06 (fictional)", address2:"", postalCode:"80123", centerClassificationDate:"20260201", initialFirmNotification:"Press Release", productQuantity:"15,000 boxes", terminationDate:"20260415" },
  { id:"F-1103-2026", recallNumber:"F-1103-2026", eventId:"90013", productDescription:"Aquafaba Powder, 500g", reasonForRecall:"Undeclared egg allergen", classification:"Class I", status:"Ongoing", distributionPattern:"Nationwide - online", recallingFirm:"Demo Ingredients 07 (fictional)", city:"Portland", state:"OR", country:"United States", recallInitiationDate:"20260310", productType:"Food", codeInfo:"Batch AP-033", moreCodeInfo:"", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 07 (fictional)", address2:"", postalCode:"97214", centerClassificationDate:"20260314", initialFirmNotification:"Letter", productQuantity:"800 pouches", terminationDate:"" },
  { id:"F-1104-2026", recallNumber:"F-1104-2026", eventId:"90014", productDescription:"Moringa Leaf Powder, 8oz pouch", reasonForRecall:"Potential Salmonella contamination", classification:"Class I", status:"Ongoing", distributionPattern:"Nationwide", recallingFirm:"Demo Botanicals 08 (fictional)", city:"Miami", state:"FL", country:"United States", recallInitiationDate:"20260120", productType:"Food", codeInfo:"Lot M-0126", moreCodeInfo:"Fictional example lots 8L5M30, 8L5M31, 8L5M32", voluntaryMandated:"Voluntary: Firm Initiated", address1:"Example address 08 (fictional)", address2:"Unit 4B", postalCode:"33132", centerClassificationDate:"20260125", initialFirmNotification:"Press Release", productQuantity:"4,200 pouches", terminationDate:"" },
]
